version: '3.8'

services:
  app:
    build: .
    container_name: stock_analysis_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=3000
    env_file:
      - .env
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge
