version: '3.8'

services:
  app:
    build: .
    container_name: go_fiber_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - go-network

  # Service untuk database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    # --- TAMBAHKAN BLOK INI ---
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ---------------------------
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

volumes:
  postgres-data: